name = "shareapp"
main = "src/worker.js"
compatibility_date = "2024-11-01"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "partage"
database_id = "bebec946-08e7-4e28-845f-995e6baa48ad"
